[project]
name = "EasyDiffraction"
description = "Diffraction data analysis"
year = 2026

[repos]
hub = "diffraction"
lib = "diffraction-lib"
app = "diffraction-app"

[urls]
hub = "https://easydiffraction.org"
lib_docs = "https://docs.easydiffraction.org/lib"
app_doc = "https://docs.easydiffraction.org/app"

[lib]
package_name = "easydiffraction"
min_python = 3.9
max_python = 3.12

[app.qtifw.setup]
version = '4.7.0'
https_mirrors = ['qt.mirror.constant.com', 'ftp.fau.de/qtproject', 'mirrors.dotsrc.org/qtproject']
base_path = 'official_releases/qt-installer-framework'
file_name_base = 'QtInstallerFramework'
file_platform = { macos = 'macOS-x64', ubuntu = 'linux-x64', windows = 'windows-x64' }
file_ext = { macos = 'dmg', ubuntu = 'run', windows = 'exe' }
installation_path = { macOS = '/Users/runner/Qt', Linux = '/home/runner/Qt', Windows = 'C:\Qt' }
